INSERT INTO mission(title) VALUES ('Accueil des étudiants');
INSERT INTO mission(title) VALUES ('Aide à l\'insertion professionelle');
INSERT INTO mission(title) VALUES ('Animation culturelles scientifiques sportives et sociales');
INSERT INTO mission(title) VALUES ('Assistance et accompagnement des étudiants handicapés');
INSERT INTO mission(title) VALUES ('Enquêtes');
INSERT INTO mission(title) VALUES ('Promotion de l\'offre de formation');
INSERT INTO mission(title) VALUES ('Secrétariat d\'examens');
INSERT INTO mission(title) VALUES ('Service d\'appui aux personnels de bibliothèque');
INSERT INTO mission(title) VALUES ('Soutien informatique et aide à l\'utilisation des nouvelles technologies');
INSERT INTO mission(title) VALUES ('Tutorat');
